name: deploy-mkdocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Instalar dependencias e tema
        run: |
          pip install mkdocs-material

      - name: Build e Deploy para o GitHub Pages
        working-directory: resumos
        run: |
          mkdocs gh-deploy --force